### PR TITLE
Use requests library in api 2.1

### PR DESCRIPTION
**Pull request by raymondk**
I ran into problems when making several queries against the load balancer where the ssl handshake would hang. Using requests (which is already in use for api 3.0) solves the problem.

### CODE REVIEW

**Comment by jeffbuttars** [comment]
If you want to see how to use requests to keep an authed session alive and login automagically, check out 
https://gitlab.boi.a10networks.com/jeffb/acos_4n/blob/sgen/target/sources/sto/setup/cm/sgen/bin/magical_rainbows/client.py

**Comment by jeffbuttars** [comment]
I think you can probably remove _a lot_ of the old code that is still there.

* Checking the socket for errno, probably don't need it.
* Using json module direclty, use requests.Response.json() instead
```
resp = requests.get(**kwargs)
...
data_struct = resp.json()
```
* What's with the all the:
```
except ....:
<do stuff>
sleep 0.1
<rinse and repeat>
```
? I think that can go because: requests.

That looks like a lot of extra error checking on the response side that is probably no longer needed?

**Comment by raymondk** [comment]
Hi, thanks for taking a look.

I agree that a lot of the extra checks are probably no longer needed but I tried in a first iteration to just drop in the requests library and keep things as close to the existing stuff as possible since I'm not familiar with the history of it.

The test suite is not passing for me but I didn't really investigate to see why. It might be that something is misconfigured but it wouldn't pass for earlier commits either.

In reply to your comments:

I'm not sure what the deal is with the 600 retries in case of some failure. It doesn't seem like a good idea to have that at all. I would have left that up to the caller to handle or at least pass the number of retries as parameter.

As far as using requests to return do r.json(), there is some code that expects the response to be xml (where it checks for the broken_replies) so I left that as it was also.

**Comment by raymondk** [comment]
And I'm not sure if it should be forced to use TLSv1.
It seems like that's being negotiated automatically.

**Comment by hthompson-a10** [comment]
PR is stale. Closing for now. Please re-open if required.

**Pull request closed without merging**
