### PR TITLE
slb.common implementation

### PR DESCRIPTION
**Pull request by mdurrant-b3**
* Provides implementation through kwargs -> dict conversion
* Minimal unit coverage that should be enough
* I don't think it will support complex params correctly

### CODE REVIEW

**Comment by Cedev** [comment]
Needs a stub in `slb` in 2.1

```
    @property
    def common(self):
        raise NotImplementedError('Some nice text about not being available in 2.1
```

**Comment by mdurrant-b3** [comment]
check

**Comment by mdurrant-b3** [comment]
These failures are due to a Jenkins failure:
    Groovy script failed:

groovy.lang.MissingPropertyException: No such property: toComputer for class: hudson.slaves.DumbSlave
Possible solutions: computer
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:50)
    at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:63)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
    at Script1.run(Script1.groovy:1)
    at groovy.lang.GroovyShell.evaluate(GroovyShell.java:580)
    at groovy.lang.GroovyShell.evaluate(GroovyShell.java:618)
    at groovy.lang.GroovyShell.evaluate(GroovyShell.java:589)
    at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:166)
    at org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildRecorder.perform(GroovyPostbuildRecorder.java:362)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
    at hudson.model.Run.execute(Run.java:1766)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:408)

**Comment by mdurrant-b3** [comment]
This passes tox on my box - I'll use the magic word to push it through the queue once the queue isn't as full.

**Pull request closed without merging**
