### PR TITLE
Include stats for service_group

### PR DESCRIPTION
**Pull request by krislindgren**

### CODE REVIEW

**Comment by dougwig** [comment]
check

**Comment by dougwig** [comment]
looks like a minor pep8 issue. plus we need to have someone here add the corresponding v30 support.

**Comment by mdurrant-b3** [comment]
Pulling this to fix pep issues... will open new PR against PEP'd branch.

**Comment by mdurrant-b3** [comment]
See https://github.com/a10networks/acos-client/pull/98

**Pull request closed without merging**
